name: Build and test 2

on: ["push"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn --frozen-lockfile --ignore-scripts

      - name: Lint
        run: yarn lint

      - name: Build check
        run: yarn lerna run build:check

      - name: Build test
        run: yarn lerna run build:test
